version: '2.1'

services:
  spring-redis:
    build: spring-redis
    mem_limit: 350m
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker

  redis-server:
    image: redis:latest
    mem_limit: 350m
    ports:
      - "6379:6379"
