spring:
  redis:
    host: localhost
    port: 6379
    password:
    jedis:
      pool:
        max-active: 16
        max-idle: 8
        min-idle: 4

---
spring:
  profiles: docker
  redis:
    host: redis-server